### ISSUE TITLE
Different behavior in `xterm` and `mlterm` possible bug?

### ISSUE THREAD

**Issue by vrthra** [saitoha/SDL1.2-SIXEL#2]
I am not sure if this is a bug in `xterm` or in `SDL-SIXEL`. I was trying to incorporate [xsw](https://github.com/NixOS/nixpkgs/pull/16582) using `sdl-sixel` in NixOS. I found that the presentation, after compiling with `sdl-sixel` instead of `sdl` would display only on `mlterm`, and not on `xterm -ti 340` where `sixel` graphics is enabled.

**Comment by saitoha** [comment]
I don't know how to reproduce this problem yet.
But I imagine that you might have to configure xterm with --enable-dec-locator.
SDL_1.2-sixel requires DEC Locator Mode to get mouse coordinate from terminals in pixel resolution.

**Comment by vrthra** [comment]
Thank you, that seems to be the issue. Sorry for bothering you.
